### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by nunojesus** [Onkelz-Freak1993/GRVL-Development#6]
Hello, I would like to design a logo for your project. Do you have something on your mind for your logo?  I can give some ideas if you are interested?
Greetings
Nuno

**Comment by Onkelz-Freak1993** [comment]
That'd be great!

At the time being, I've got no idea how it ahould loog like. maybe a PickUp-bolt in grey-blue, like the webpage www.gingolingoo.de or something.

The Gray is: #202020 or #303030
The Blue is: #33b5e5

**Comment by Onkelz-Freak1993** [comment]
sorry, should*  and look*

stupid phone :/

**Comment by Onkelz-Freak1993** [comment]
https://steamuserimages-a.akamaihd.net/ugc/96105264963971412/ABF47E007A350D1E4161BDED9E96680000C445A3/

this thunderbolt is the pickup bolt i mentioned.

and yes. it is for multiplayer races and -connections, as well as managing mods and friends.

**Comment by Onkelz-Freak1993** [comment]
![](https://i.imgur.com/88YC9fY.png) here a more detailed image.

**Comment by nunojesus** [comment]
Ok, I will start now!
Greetings!

**Comment by nunojesus** [comment]
Hi Im Finishing the logo design, I will send you really soon.

**Comment by nunojesus** [comment]
Hello, here is my work, I hope you like it.
Just tell me if you like it  or not, and if you want any changes.
I put the colours of your website, and I provide also the back and white and other va
riations too.
![bolt](https://user-images.githubusercontent.com/34600369/39087852-29d3ccee-459f-11e8-9c00-93af15611d07.png)


![bolt varios](https://user-images.githubusercontent.com/34600369/39087858-4783ef62-459f-11e8-9ab5-c660a8270edf.png)

**Comment by Onkelz-Freak1993** [comment]
dude, these are amazing!!

**Comment by nunojesus** [comment]
My happy you like it.
Are you going to use them? I will prepair the files for you, png with transparency.
I will try to send them to you  tomorrow or maybe on monday, ok?
Greetings!

**Comment by Onkelz-Freak1993** [comment]
yes, definately!!
don't rush, take your time. i'm amazed you did them so quickly. thank you again!

**Comment by nunojesus** [comment]
Hello, I have all the files to send you, Im trying to make a pull request, but Im having problems with it.
How can I do it.

Greetings

**Comment by Onkelz-Freak1993** [comment]
https://github.com/Onkelz-Freak1993/GRVL-Development/compare

click here on 'Create Pull Request'

**Comment by nunojesus** [comment]
Im trying to do but It doesnt let me do it. I will try tomorrow.

Here is the link with the logos, I send png, pdf, svg and eps files.

When you used just tell me to see how it looks.

https://drive.google.com/drive/folders/14Cen1Vg_lZ5uzuO0McAyb1lhi1a8aWEc?usp=sharing

If you want some changes just tell me.

Greetings

**Comment by nunojesus** [comment]
Hey did you download the files?
Do you want any change?
Im trying to make the pull request but it wont lat me.

**Comment by Onkelz-Freak1993** [comment]
i'm currently on my way home, then i'll download the files. will tell you when i'm home.

contact me on Discord, if you want: Onkelz-Freak1993#0001

**Comment by Onkelz-Freak1993** [comment]
i'm currently on my way home, then i'll download the files. will tell you when i'm home.

contact me on Discord, if you want: Onkelz-Freak1993#0001

**Comment by Onkelz-Freak1993** [comment]
i downloaded the files, and got no changes for now.
but one question, whats the font's name you used?

**Comment by nunojesus** [comment]
The font is SLANT. Did you merged my pull request? Can you put the logotype in the README file of your repository, and please can give me the credits :) Thank you very much

**Comment by Onkelz-Freak1993** [comment]
i merged your pull request :)

**Comment by Onkelz-Freak1993** [comment]
https://i.imgur.com/YDJ7qRN.png  here you go. :) Thank you again.

will put the logotype into the readme tomorrow.

**Comment by nunojesus** [comment]
You dont need to thank me, if you need something else just say it.
